# Generated by Django 3.1.4 on 2021-01-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20201228_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taxi.company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taxi.vehicle'),
        ),
    ]
