# Generated by Django 3.1.4 on 2021-01-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20210101_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_production',
            field=models.IntegerField(verbose_name='year of production'),
        ),
    ]
