# Generated by Django 3.1.4 on 2021-01-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_auto_20210102_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='taxi.driver'),
            preserve_default=False,
        ),
    ]
