# Generated by Django 3.1.4 on 2021-01-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20210102_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
